const PHOTOS = {
  // Platos
  pastaGambas:    'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=900&q=85&auto=format&fit=crop',
  albondigas:     'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=900&q=85&auto=format&fit=crop',
  salmon:         'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=900&q=85&auto=format&fit=crop',
  polloHorno:     'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=900&q=85&auto=format&fit=crop',
  atunPakChoi:    'https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=85&auto=format&fit=crop',
  costillas:      'https://images.unsplash.com/photo-1558030006-450675393462?w=900&q=85&auto=format&fit=crop',
  lentejas:       'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=900&q=85&auto=format&fit=crop',
  alitas:         'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=900&q=85&auto=format&fit=crop',
  arrozBogavante: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=900&q=85&auto=format&fit=crop',
  sopaMarisco:    'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=900&q=85&auto=format&fit=crop',
  caldoSetas:     'https://images.unsplash.com/photo-1608500218890-c4f9c9e81c4c?w=900&q=85&auto=format&fit=crop',
  cordero:        'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=900&q=85&auto=format&fit=crop',
  patasCerdo:     'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=900&q=85&auto=format&fit=crop',
  cabraEstofada:  'https://images.unsplash.com/photo-1574484284002-952d92456975?w=900&q=85&auto=format&fit=crop',
  ensaladaNorm:   'https://images.unsplash.com/photo-1551248429-40975aa4de74?w=900&q=85&auto=format&fit=crop',
  cobbSalad:      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900&q=85&auto=format&fit=crop',
  hotPot:         'https://images.unsplash.com/photo-1547592180-85f173990554?w=900&q=85&auto=format&fit=crop',
  berberechos:    'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=900&q=85&auto=format&fit=crop',
  setasEsp:       'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&q=85&auto=format&fit=crop',
  // Repostería / Postres
  casadielles:    'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900&q=85&auto=format&fit=crop',
  scones:         'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=900&q=85&auto=format&fit=crop',
  pureManzana:    'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=900&q=85&auto=format&fit=crop',
  crepes:         'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=900&q=85&auto=format&fit=crop',
  bizcocho:       'https://images.unsplash.com/photo-1606756790138-261d2b21cd75?w=900&q=85&auto=format&fit=crop',
  magdalenas:     'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=900&q=85&auto=format&fit=crop',
  pretzels:       'https://images.unsplash.com/photo-1573821663912-569905455b1c?w=900&q=85&auto=format&fit=crop',
  // Platos enlazados
  panangChicken:  'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=900&q=85&auto=format&fit=crop',
  kimchi:         'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=900&q=85&auto=format&fit=crop',
  samgyeopsal:    'https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=85&auto=format&fit=crop',
  vongole:        'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=900&q=85&auto=format&fit=crop',
};

export const IMPORT_PHOTO = PHOTOS.cobbSalad;

export const INITIAL_RECIPES = [
  // ── PLATOS ──────────────────────────────────────────────────────────
  {
    id: 1, title: 'Pasta con gambas', category: 'Platos', time: '20m', servings: 2,
    favourite: true, photo: PHOTOS.pastaGambas, source: 'Alicia',
    note: 'La salsa china de rollitos hace toda la diferencia — un umami sorprendente.',
    ingredients: [
      '200 g de pasta (espaguetis o linguine)',
      'Gambas medianas (unas 10–12)',
      '2 dientes de ajo laminados',
      '2 cdas de salsa de rollitos de primavera china',
      'Zumo de ½ limón',
      'Aceite de oliva, sal',
    ],
    steps: [
      'Cocer la pasta en agua bien salada hasta al dente.',
      'En una sartén grande, sofreír el ajo en aceite a fuego medio hasta dorar.',
      'Añadir las gambas y la salsa de rollitos; rehogar hasta que las gambas estén rosadas.',
      'Escurrir la pasta y mezclarla en la sartén.',
      'Exprimir el limón por encima, remover y servir enseguida.',
    ],
  },
  {
    id: 2, title: 'Albóndigas en salsa', category: 'Platos', time: '45m', servings: 4,
    favourite: false, photo: PHOTOS.albondigas, source: 'Familia',
    note: 'El truco está en dorar bien las albóndigas antes de añadir la salsa — así no se deshacen.',
    ingredients: [
      '500 g de carne picada mixta (ternera y cerdo)',
      '1 huevo',
      '2 dientes de ajo rallados',
      'Pan rallado, sal y pimienta',
      '1 cebolla grande',
      '2 zanahorias',
      '1 cdta de harina',
      '1 vaso de vino blanco',
      'Agua o caldo',
      'Aceite de oliva',
    ],
    steps: [
      'Mezclar la carne picada con el huevo, el ajo, pan rallado, sal y pimienta. Formar las albóndigas.',
      'Freír las albóndigas en aceite caliente para dorar y sellar por fuera. Reservar.',
      'En la misma sartén, hacer un sofrito con la cebolla y las zanahorias.',
      'Añadir la cucharadita de harina y remover. Verter el vino blanco y dejar evaporar.',
      'Echar agua o caldo hasta cubrir y, cuando hierva, colocar las albóndigas encima.',
      'Hervir a fuego lento 20–25 minutos hasta que la salsa espese.',
    ],
  },
  {
    id: 3, title: 'Salmón a la parrilla', category: 'Platos', time: '25m', servings: 2,
    favourite: false, photo: PHOTOS.salmon, source: 'Alicia',
    note: 'Las verduras asadas alrededor del salmón quedan perfectas con un poco de limón al final.',
    ingredients: [
      '2 lomos de salmón',
      'Verduras variadas en rodajas (calabacín, pimiento, berenjena)',
      'Zumo de ½ limón',
      'Aceite de oliva',
      'Sal y pimienta negra',
    ],
    steps: [
      'Calentar la parrilla a fuego fuerte.',
      'Cortar las verduras en rodajas, pincelar con aceite y sal, y asar hasta que estén hechas.',
      'Desplazar las verduras hacia los bordes de la parrilla.',
      'Colocar el salmón en el centro con un chorrito de aceite y sal. Asar 3–4 min por lado.',
      'Exprimir el limón por encima y añadir pimienta negra al gusto.',
    ],
  },
  {
    id: 4, title: 'Pollo entero al horno', category: 'Platos', time: '1h 45m', servings: 4,
    favourite: true, photo: PHOTOS.polloHorno, source: 'Familia',
    note: 'Una cerveza a mitad de cocción mantiene la pechuga jugosa y le da un toque increíble.',
    ingredients: [
      '1 pollo entero (aprox. 1,5–1,8 kg)',
      '1 cabeza de ajos sin pelar',
      '1 limón partido',
      'Hierbas al gusto (tomillo, romero, orégano)',
      'Aceite de oliva',
      'Sal y pimienta',
      '½ lata de cerveza o vaso de vino blanco',
    ],
    steps: [
      'Precalentar el horno a 180 °C.',
      'Untar el pollo por fuera con aceite, sal y las hierbas.',
      'Meter en la cavidad los ajos sin pelar y el limón partido.',
      'Asar 45 minutos. A mitad de cocción, verter la cerveza o el vino por encima.',
      'Continuar otros 45–50 minutos hasta que esté dorado y los jugos salgan claros al pinchar el muslo.',
    ],
  },
  {
    id: 5, title: 'Atún con pak choi', category: 'Platos', time: '20m', servings: 2,
    favourite: false, photo: PHOTOS.atunPakChoi, source: 'Alicia',
    note: 'Dos sartenes a la vez — una para cada ingrediente — y el plato se hace en minutos.',
    ingredients: [
      '2 filetes gruesos de atún fresco',
      '2 pak choi, cortados en trozos',
      '4 dientes de ajo laminados',
      '1 trozo de jengibre fresco rallado',
      'Caldo de pollo tipo Maggi (un chorrito)',
      'Salsa de soja',
      'Zumo de ½ limón',
      'Aceite de oliva, sal, perejil fresco',
    ],
    steps: [
      'Cortar el atún en dados. Salpimentar y espolvorear con perejil picado.',
      'En una sartén con aceite, sofreír la mitad del ajo. Añadir el atún y dorar cada lado brevemente. Al final, exprimir el limón.',
      'En otra sartén, sofreír el resto del ajo con el jengibre en aceite.',
      'Añadir el pak choi y rehogar. Verter un chorrito de caldo Maggi y la salsa de soja; remover hasta que esté tierno.',
      'Servir el pak choi como base con el atún encima.',
    ],
  },
  {
    id: 6, title: 'Costillas con patatas', category: 'Platos', time: '1h 30m', servings: 4,
    favourite: false, photo: PHOTOS.costillas, source: 'Familia',
    note: 'Las patatas en cachelos absorben todo el guiso — lo mejor del plato.',
    ingredients: [
      '800 g de costillas de cerdo',
      '2 patatas grandes en cachelos',
      '1 cebolla',
      '1 pimiento verde',
      '1 puerro',
      '½ tomate maduro',
      '2 dientes de ajo',
      '1 vaso de vino blanco',
      'Pimentón dulce',
      'Aceite de oliva, sal',
    ],
    steps: [
      'Calentar aceite en una olla y rehogar las costillas con sal y ajo hasta dorar.',
      'Añadir la cebolla, el pimiento, el puerro y el tomate en trozos grandes. Sofreír unos minutos.',
      'Verter el vino blanco y dejar evaporar.',
      'Añadir un poco de agua, tapar y cocer a fuego lento 45 minutos.',
      'Cuando la carne esté casi hecha, añadir el pimentón y las patatas en cachelos.',
      'Cubrir de agua, hervir fuerte y luego bajar a fuego lento 15 minutos hasta que las patatas estén tiernas.',
    ],
  },
  {
    id: 7, title: 'Lentejas con verdura', category: 'Platos', time: '55m', servings: 4,
    favourite: false, photo: PHOTOS.lentejas, source: 'Familia',
    note: 'Todo en crudo y a cocer — no hay sofrito, es la receta de las lentejas de siempre.',
    ingredients: [
      '1 taza de lentejas pardinas',
      '3,5 tazas de agua',
      '1 zanahoria en rodajas',
      '1 puerro en rodajas',
      '1 cebolla troceada',
      '2 dientes de ajo',
      '1 hoja de laurel',
      '½ cdta de comino',
      'Aceite de oliva',
      'Sal',
    ],
    steps: [
      'Poner las lentejas (sin remojar), las verduras, el ajo, el laurel y el comino en una olla.',
      'Cubrir con el agua, añadir un chorrito de aceite y sal.',
      'Llevar a ebullición a fuego fuerte.',
      'Bajar a fuego mínimo, tapar y cocer 40 minutos.',
      'Rectificar de sal. Opcional: retirar el laurel y triturar una parte para darle más cuerpo.',
    ],
  },
  {
    id: 8, title: 'Alitas de pollo al horno', category: 'Platos', time: '50m', servings: 2,
    favourite: false, photo: PHOTOS.alitas, source: 'Alicia',
    note: 'La clave es darles la vuelta a mitad y los últimos minutos bien fuerte para que queden crujientes.',
    ingredients: [
      '6 alitas de pollo',
      '3 dientes de ajo machacados',
      '1 cdta de pimentón dulce',
      'Zumo de ½ limón',
      '1 vaso de vino blanco o cerveza',
      'Aceite de oliva, sal',
    ],
    steps: [
      'Precalentar el horno a 200–220 °C.',
      'Mezclar las alitas con el ajo, el pimentón, el limón, la cerveza y aceite. Salar.',
      'Colocar en la bandeja a media altura y hornear 20 minutos.',
      'Dar la vuelta y hornear otros 20 minutos.',
      'Subir a 220 °C y hornear 10 minutos más por cada lado para dorar bien.',
    ],
  },
  {
    id: 9, title: 'Arroz con bogavante', category: 'Platos', time: '1h', servings: 4,
    favourite: true, photo: PHOTOS.arrozBogavante, source: 'Familia',
    note: 'El caldo casero de cabezas de langostino es lo que convierte este arroz en algo especial.',
    ingredients: [
      '1 bogavante mediano, troceado',
      '200 g de langostinos (pelar y guardar cáscaras)',
      '200 g de almejas',
      '1,5 vasos de arroz bomba',
      '6 vasos de caldo (de las cabezas y cáscaras)',
      '1 cebolla',
      '2 dientes de ajo',
      '1 pimiento rojo',
      '2 tomates maduros',
      'Un toque de picante',
      'Aceite de oliva, sal',
    ],
    steps: [
      'Caldo: freír las cáscaras y cabezas de langostino hasta que estén rojas. Cubrir de agua y hervir 20 min. Colar.',
      'Freír los trozos de bogavante en aceite caliente hasta que estén rojos. Reservar.',
      'En el mismo aceite, sofreír la cebolla, el ajo y el pimiento. Añadir el tomate y un poco de picante.',
      'Añadir las almejas y dejar que abran.',
      'Incorporar el arroz y sofreír 1 minuto. Añadir el bogavante y verter el caldo caliente.',
      'Cocer a fuego vivo 8 min, luego a fuego medio otros 8 min.',
      'Añadir los langostinos pelados los últimos 3 min. Reposar 5 min antes de servir.',
    ],
  },
  {
    id: 10, title: 'Sopa de marisco', category: 'Platos', time: '1h', servings: 4,
    favourite: false, photo: PHOTOS.sopaMarisco, source: 'Familia',
    note: 'Restos de pescado para el caldo y almejas frescas para el sofrito — la combinación perfecta.',
    ingredients: [
      'Carcasa de merluza (cabeza, cola, espina)',
      '1 puerro',
      '1 cebolla',
      '200 g de almejas (en remojo en agua con sal)',
      '200 g de gambas peladas',
      '1 diente de ajo',
      'Maicena (opcional, para espesar)',
      'Sal, aceite de oliva',
    ],
    steps: [
      'Caldo: poner la carcasa, el puerro y media cebolla en agua. Llevar a ebullición, espumar y cocer 30 min a fuego lento. Colar.',
      'En otra olla, sofreír la cebolla restante y el ajo (añadir maicena si se desea más espeso).',
      'Añadir las almejas al sofrito y esperar que abran. Retirar la mitad de las cáscaras.',
      'Verter el caldo colado sobre el sofrito.',
      'Añadir las gambas peladas. Cocer a fuego mínimo tapado 10 min más. Rectificar de sal.',
    ],
  },
  {
    id: 11, title: 'Caldo de setas', category: 'Platos', time: '1h 30m', servings: 4,
    favourite: false, photo: PHOTOS.caldoSetas, source: 'Alicia',
    note: 'El hueso de jamón da al caldo una profundidad que ningún caldo de brick puede igualar.',
    ingredients: [
      '½ puerro',
      '1 hueso de jamón',
      '150 g de setas oyster',
      '2 dientes de ajo',
      '100 g de gambas peladas',
      'Especias al gusto (pimienta, laurel)',
      'Sal, aceite de oliva',
    ],
    steps: [
      'En una olla grande, sofreír el puerro en aceite a fuego medio.',
      'Añadir el hueso de jamón y las setas troceadas.',
      'Incorporar el ajo y las gambas. Rehogar brevemente.',
      'Cubrir con agua abundante, añadir las especias y sal.',
      'Llevar a ebullición y cocer a fuego mínimo durante 1 hora, tapado.',
      'Colar y servir como consomé, o usar como base para arroces y sopas.',
    ],
  },
  {
    id: 12, title: 'Cordero al horno', category: 'Platos', time: '1h', servings: 4,
    favourite: false, photo: PHOTOS.cordero, source: 'Familia',
    note: 'Sencillo y sin pretensiones — la carne habla sola.',
    ingredients: [
      '1 pierna o paletilla de cordero',
      '4–5 dientes de ajo',
      'Especias al gusto (romero, tomillo, pimienta)',
      'Aceite de oliva',
      'Sal',
      '1 vaso de agua',
    ],
    steps: [
      'Precalentar el horno a 180 °C.',
      'Colocar el cordero en la bandeja, salar y cubrir con aceite por encima.',
      'Añadir los dientes de ajo, las especias y el vaso de agua en la bandeja.',
      'Hornear 20 minutos por cada lado.',
      'Añadir un poco más de agua a mitad si la bandeja se seca demasiado.',
    ],
  },
  {
    id: 13, title: 'Patas de cerdo estofadas', category: 'Platos', time: '2h', servings: 4,
    favourite: false, photo: PHOTOS.patasCerdo, source: 'Alicia',
    note: 'Receta de inspiración asiática — el anís estrellado y el clavo hacen que sea diferente a todo.',
    ingredients: [
      '4 patas de cerdo, cortadas en cuatro',
      '4 dientes de ajo',
      '1 trozo de jengibre fresco',
      '2 anís estrellado',
      '2 clavos',
      'Semillas de hinojo',
      '2 hojas de laurel',
      '1 cayena',
      '2 cebolletas picadas',
      'Salsa de soja',
      '1 vaso de vino Shaoxing o vino blanco',
    ],
    steps: [
      'Hervir las patas en agua con laurel, jengibre y cebolla durante 15 min. Espumar bien y escurrir.',
      'Calentar aceite en un wok o cazuela grande.',
      'Sofreír el ajo, el jengibre, el anís, el clavo, el laurel, la cayena y las semillas de hinojo.',
      'Añadir las patas y dorar removiendo.',
      'Incorporar la cebolleta picada, la soja y el vino.',
      'Cubrir de agua, llevar a ebullición y cocer a fuego lento hasta que la carne esté muy tierna (1–1,5 h).',
    ],
  },
  {
    id: 14, title: 'Cabra estofada', category: 'Platos', time: '1h 45m', servings: 4,
    favourite: false, photo: PHOTOS.cabraEstofada, source: 'Familia',
    note: 'Guiso de los de antes — mejor al día siguiente cuando los sabores se asientan.',
    ingredients: [
      '1 kg de carne de cabra',
      '1 cebolla',
      '1 pimiento verde',
      '2 tomates en trozos',
      '1 vaso de vino tinto',
      '2 hojas de laurel',
      'Tomillo',
      '2 patatas grandes en cachelos',
      'Aceite de oliva, sal',
    ],
    steps: [
      'En una cazuela, sofreír la cebolla y el pimiento en aceite.',
      'Salar la cabra y rehogar en la misma cazuela, removiendo hasta dorar.',
      'Añadir el tomate en cachos, el tomillo y el laurel.',
      'Verter el vino tinto y dejar evaporar el alcohol.',
      'Cubrir con agua, llevar a ebullición, tapar y cocer a fuego bajo-medio 1 hora.',
      'Añadir las patatas en cachelos y cocer 30 minutos más.',
    ],
  },
  {
    id: 15, title: 'Ensalada normanda', category: 'Platos', time: '20m', servings: 2,
    favourite: false, photo: PHOTOS.ensaladaNorm, source: 'Familia',
    note: 'La combinación de lardons, piñones y queso emmental rebozado la convierte en una ensalada de verdad.',
    ingredients: [
      '1 cogollo de lechuga',
      '2 tomates',
      'Lardons (panceta en dados)',
      '½ cebolla roja en juliana',
      'Piñones tostados',
      '2 lonchas de queso emmental, rebozadas y fritas',
      '2 huevos cocidos, en cuartos',
      '1 manzana en láminas',
      'Vinagreta al gusto',
    ],
    steps: [
      'Freír los lardons en sartén sin aceite hasta que estén crujientes. Reservar.',
      'Rebozar el queso emmental en huevo y pan rallado y freír en aceite caliente.',
      'Montar la ensalada con la lechuga, el tomate, la cebolla, la manzana y los piñones.',
      'Añadir los lardons y los huevos cocidos.',
      'Colocar el queso emmental caliente encima y aliñar con la vinagreta.',
    ],
  },
  {
    id: 16, title: 'Cobb salad St. Lucía', category: 'Platos', time: '30m', servings: 2,
    favourite: false, photo: PHOTOS.cobbSalad, source: 'St. Lucía · 2024',
    note: 'La vinagreta de piña y jengibre es el secreto — ácida, fresca y totalmente tropical.',
    ingredients: [
      '1 pechuga de pollo al estilo jerk',
      '4 lonchas de bacon frito',
      '2 huevos duros en cuartos',
      '½ cebolla en juliana',
      '4 hojas de lechuga',
      'Maíz dulce',
      '1 zanahoria rallada (poca)',
      '½ pepino en rodajas',
      '1 tomate',
      'Col lombarda rallada',
      '— Aliño —',
      '3 cdas de piña triturada',
      '1 cdta de jengibre fresco rallado',
    ],
    steps: [
      'Preparar el pollo jerk (marinado con especias caribeñas) a la parrilla o al horno.',
      'Freír el bacon hasta crujiente.',
      'Cocer los huevos 8 minutos, enfriar y pelar.',
      'Disponer todos los ingredientes en filas sobre la lechuga: pollo, bacon, huevo, maíz, cebolla, pepino, zanahoria, tomate y lombarda.',
      'Mezclar la piña triturada con el jengibre y un poco de aceite. Verter por encima.',
    ],
  },
  {
    id: 17, title: 'Hot pot de callos mala', category: 'Platos', time: '1h', servings: 4,
    favourite: false, photo: PHOTOS.hotPot, source: 'Alicia · 2026',
    note: '«Siete arriba, ocho abajo» — el secreto para que los callos queden tiernos y no gomosos.',
    ingredients: [
      '500 g de callos de ternera (maodu), en láminas finas',
      '1 paquete de base de hot pot mala (Haidilao, Little Sheep...)',
      '1,5 L de caldo de pollo o agua',
      '2 dientes de ajo',
      '3 lonchas de jengibre',
      '1 cebolleta',
      '— Acompañamientos —',
      'Col china, tofu, setas enoki, fideos de arroz',
      '— Salsa de mojado —',
      '1 cda de aceite de sésamo',
      '1 cda de ajo picado',
      '1 cda de cilantro fresco',
      '1 cda de cebolleta picada',
      '1 cdta de salsa de soja',
    ],
    steps: [
      'Añadir el agua o caldo a la olla. Echar la base de hot pot, el ajo, el jengibre y la cebolleta.',
      'Llevar a ebullición y mantener a fuego vivo en el fogón de mesa.',
      'Preparar la salsa de mojado mezclando el aceite de sésamo, el ajo, el cilantro, la cebolleta y la soja.',
      'Cocer los callos con la técnica «siete arriba, ocho abajo»: agitarlos en el caldo hirviendo 10–15 segundos.',
      'Retirar cuando los bordes estén ligeramente curvados — tiernos pero con mordida.',
      'Mojar en la salsa de sésamo y comer. Ir añadiendo verduras y fideos al caldo a lo largo de la comida.',
    ],
  },
  // ── ENTRANTES ───────────────────────────────────────────────────────
  {
    id: 18, title: 'Berberechos al ajillo', category: 'Entrantes', time: '15m', servings: 2,
    favourite: false, photo: PHOTOS.berberechos, source: 'Familia',
    note: 'Media hora en agua con sal para que suelten la arena — no saltarse este paso.',
    ingredients: [
      '400 g de berberechos frescos',
      '3 dientes de ajo laminados',
      '1 guindilla (opcional)',
      '½ vaso de vino blanco',
      'Aceite de oliva, sal',
      'Perejil fresco',
    ],
    steps: [
      'Dejar los berberechos en agua con sal media hora para que suelten la arena. Lavar bien.',
      'En una sartén amplia, calentar aceite y dorar el ajo laminado (y la guindilla si se usa).',
      'Subir el fuego y añadir los berberechos con el vino blanco.',
      'Tapar y agitar la sartén 2–3 minutos hasta que abran.',
      'Espolvorear con perejil picado y servir con pan.',
    ],
  },
  {
    id: 19, title: 'Setas con espinacas', category: 'Entrantes', time: '15m', servings: 2,
    favourite: false, photo: PHOTOS.setasEsp, source: 'Alicia',
    note: 'El aceite de coco con mucho ajo es la base — el secreto de un salteado sabroso sin agua.',
    ingredients: [
      '200 g de setas variadas (shiitake, ostra, champiñón)',
      '100 g de espinacas frescas',
      '4 dientes de ajo picados generosamente',
      '1 cda de aceite de coco',
      'Sal',
    ],
    steps: [
      'Calentar el aceite de coco en una sartén grande a fuego medio-alto.',
      'Añadir el ajo y sofreír hasta que empiece a dorar.',
      'Incorporar las setas troceadas y rehogar hasta que estén tiernas y sin agua.',
      'Añadir las espinacas frescas, salar y remover hasta que se reduzcan. Servir enseguida.',
    ],
  },
  // ── REPOSTERÍA / POSTRES ─────────────────────────────────────────────
  {
    id: 20, title: 'Casadielles', category: 'Repostería', time: '1h 30m', servings: 12,
    favourite: true, photo: PHOTOS.casadielles, source: 'Familia · Asturias',
    note: 'El aceite frito con un currusco de pan es el truco familiar que hace la masa especial.',
    ingredients: [
      '½ taza de vino blanco',
      '½ taza de agua templada con 1 cdta de sal',
      '50 g de mantequilla derretida',
      '½ taza de aceite (frito con un currusco de pan hasta que esté)',
      '1 huevo',
      'Harina la que admita (aprox. 300–350 g)',
      '2 cdtas de polvo de hornear',
      '— Relleno —',
      'Nueces molidas',
      'Azúcar y anís al gusto',
    ],
    steps: [
      'Batir bien el vino, el agua con sal, la mantequilla, el aceite frito y el huevo.',
      'Ir añadiendo harina tamizada con el polvo de hornear hasta obtener una masa blanda que no se pegue.',
      'Amasar brevemente. Estirar, doblar dos o tres veces, hacer una bola y guardar en la nevera 30 min envuelta en plástico.',
      'Extender la masa fina y cortar en rectángulos.',
      'Poner una cucharada del relleno de nueces con azúcar y anís en el centro, doblar y sellar bien los bordes.',
      'Freír en aceite abundante a fuego medio hasta dorar por ambos lados.',
      'Escurrir y espolvorear con azúcar glas.',
    ],
  },
  {
    id: 21, title: 'Scones fluffy', category: 'Repostería', time: '25m', servings: 8,
    favourite: false, photo: PHOTOS.scones, source: 'Alicia',
    note: 'No amasar demasiado — la clave para que queden esponjosos y altos.',
    ingredients: [
      '90 g de mantequilla fría en dados',
      '1½ tazas de harina',
      '1 cdta de baking powder',
      '¼ cdta de sal',
      '2 cdas de azúcar glas',
      '1 cdta de zumo de limón',
      '180 ml de leche',
      '1 cdta de extracto de vainilla',
    ],
    steps: [
      'Precalentar el horno a 200 °C.',
      'Mezclar la harina, el baking powder, la sal y el azúcar. Añadir la mantequilla en dados.',
      'Frotar con los dedos hasta obtener migas gruesas. Añadir el zumo de limón.',
      'Incorporar la leche con la vainilla y mezclar brevemente — no amasar.',
      'Extender la masa a 4 cm de grosor y cortar en 8 porciones.',
      'Hornear 12 minutos hasta que estén dorados. Servir calientes con mantequilla y mermelada.',
    ],
  },
  {
    id: 22, title: 'Puré de manzana', category: 'Postres', time: '30m', servings: 4,
    favourite: false, photo: PHOTOS.pureManzana, source: 'Familia',
    note: 'Mezclar reineta y golden le da profundidad — ni muy ácido ni demasiado dulce.',
    ingredients: [
      '4–5 manzanas (reineta y golden a partes iguales)',
      '50 g de mantequilla',
      '1 rama de canela',
      '3–4 clavos',
      '2–3 cdas de azúcar',
      'Un chorrito de agua',
    ],
    steps: [
      'Pelar las manzanas y cortarlas en trozos pequeños.',
      'Fundir la mantequilla en una cazuela. Añadir la canela y los clavos.',
      'Añadir la manzana y rehogar unos minutos.',
      'Echar el azúcar y un chorrito de agua. Cocer tapado hasta que la manzana esté muy blanda (15–20 min).',
      'Retirar la canela y los clavos. Triturar hasta obtener un puré liso.',
    ],
  },

  // ── RECETAS ENLAZADAS ────────────────────────────────────────────────
  {
    id: 23, title: 'Crepes de canela', category: 'Repostería', time: '30m', servings: 4,
    favourite: false, photo: PHOTOS.crepes,
    source: 'BBC Good Food',
    link: 'https://www.bbcgoodfood.com/recipes/cinnamon-pancakes-compote-maple-syrup',
    note: 'Añadir canela en polvo a la masa. Freír con mitad aceite de coco y mitad mantequilla.',
    ingredients: [],
    steps: ['Ver receta completa en el enlace →'],
  },
  {
    id: 24, title: 'Panang chicken stir-fry', category: 'Platos', time: '30m', servings: 4,
    favourite: false, photo: PHOTOS.panangChicken,
    source: 'BBC Food',
    link: 'https://www.bbc.co.uk/food/recipes/panang_chicken_stir-fry_00869',
    note: 'Curry panang tailandés — aromático, cremoso y con el punto justo de picante.',
    ingredients: [],
    steps: ['Ver receta completa en el enlace →'],
  },
  {
    id: 25, title: 'Bizcocho de plátano', category: 'Repostería', time: '1h 10m', servings: 8,
    favourite: false, photo: PHOTOS.bizcocho,
    source: 'Recetas Americanas',
    link: 'http://recetasamericanas.com/2012/01/02/mejor-bizcocho-de-platano-banana-bread-americano/',
    note: 'El mejor banana bread americano — perfecto para plátanos muy maduros.',
    ingredients: [],
    steps: ['Ver receta completa en el enlace →'],
  },
  {
    id: 26, title: 'Pretzels de canela y azúcar', category: 'Repostería', time: '1h', servings: 8,
    favourite: false, photo: PHOTOS.pretzels,
    source: 'One Little Project',
    link: 'http://onelittleproject.com/cinnamon-sugar-soft-pretzels/',
    note: 'Pretzels blandos con cobertura de canela y azúcar — para compartir en familia.',
    ingredients: [],
    steps: ['Ver receta completa en el enlace →'],
  },
  {
    id: 27, title: 'Magdalenas caseras', category: 'Repostería', time: '35m', servings: 12,
    favourite: false, photo: PHOTOS.magdalenas,
    source: 'Recetas de Rechupete',
    link: 'https://www.recetasderechupete.com/como-preparar-magdalenas-caseras-receta-paso-a-paso/7789/',
    note: 'La receta clásica de magdalenas esponjosas — con el copete bien subido.',
    ingredients: [],
    steps: ['Ver receta completa en el enlace →'],
  },
  {
    id: 28, title: 'Kimchi bokkeumbap', category: 'Platos', time: '20m', servings: 2,
    favourite: false, photo: PHOTOS.kimchi,
    source: 'Maangchi',
    link: 'https://www.maangchi.com/recipe/kimchi-bokkeumbap',
    note: 'Arroz frito con kimchi coreano — rápido, sabroso y con mucho umami.',
    ingredients: [],
    steps: ['Ver receta completa en el enlace →'],
  },
  {
    id: 29, title: 'Samgyeopsal-gui', category: 'Platos', time: '30m', servings: 4,
    favourite: false, photo: PHOTOS.samgyeopsal,
    source: 'Maangchi',
    link: 'https://www.maangchi.com/recipe/samgyeopsal-gui',
    note: 'Panceta de cerdo a la parrilla al estilo coreano — con lechuga, ajo asado y pasta gochujang.',
    ingredients: [],
    steps: ['Ver receta completa en el enlace →'],
  },
  {
    id: 30, title: 'Espaguetis alle vongole', category: 'Platos', time: '25m', servings: 2,
    favourite: false, photo: PHOTOS.vongole,
    source: 'YouTube',
    link: 'https://youtu.be/F9K9gc1uf78?feature=shared',
    note: 'La técnica italiana clásica — almejas, vino blanco, ajo y la pasta bien al dente.',
    ingredients: [],
    steps: ['Ver receta completa en el enlace →'],
  },
];
